version: "3.9"

services:
  dash_app:
    environment:
      - METRICS_PATH=/app/database/json/shared_metrics
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./database/json:/app/database/json
      - ./database/sqlite:/app/database/sqlite
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 512M
