version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  streamlit-app:
    build: .
    container_name: streamlit_monitoring_app
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./dashboard:/app/dashboard
      - ./database:/app/database
    command: bash start.sh
    

volumes:
  mysql_data:
