# Dockerfile.dashboard
FROM python:3.12-slim

WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt .
COPY dashboard/ dashboard/
COPY database/ database/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "dashboard/dash_app.py"]
